baseURL = "https://Hammaduddin561.github.io/"
title = "Md Hammaduddin"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

pygmentsStyle = "monokai"

[params]
  footer = "Md Hammaduddin"
  description = "Open Source Developer"
  ShowBackToTopButton = true
  avatarURL = "/images/avatar.jpg"
  avatarSize = "size-m"
  showPostsOnHomePage = "recent"
  numberPostsOnHomePage = 5
  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/hammaduddin57/"},
    {name = "github", url = "https://github.com/Hammaduddin561"},
    {name = "email", url = "mailto:hammaduddin57@gmail.com"}
  ]

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/Hammaduddin561"
    weight = 3

  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false
