baseURL = "https://Hammaduddin561.github.io/"
title = "Hammaduddin"
theme = "gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true

pygmentsStyle = "monokai"

[params]
  footer = "Md Hammaduddin"
  description = "Open Source Developer & LFX Mentee"
  ShowBackToTopButton = true
  avatarURL = "/images/avatar.jpg"
  avatarSize = "size-m"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    pre = "book"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "LFX Report"
    pre = "file-text"
    url = "/posts/lfx/lfx_final/"
    weight = 3

  [[menu.main]]
    name = "GitHub"
    pre = "github"
    url = "https://github.com/Hammaduddin561"
    weight = 4
